### ISSUE TITLE
react is not defined

### ISSUE THREAD

**Issue by Necmttn** [weflex/react-baidu-map#2]
react-baidu-map.js:146 Uncaught ReferenceError:

**Comment by yorkie** [comment]
You should expose react as a global object in runtime :)

**Comment by FateRiddle** [comment]
How do I expose react as a global object in runtime? And it is kinda ridiculous users have to set things up just for this library to work.

**Comment by imink** [comment]
@FateRiddle it is a typo. open the console, you'll find the error line in the source code, change the react to React.

**Comment by Doelove** [comment]
@imink  change the react to React.  result: React is not defined  ...
